version: 2.1

jobs:

  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: UdaPeople_Product-{{ checksum "package-lock.json" }}
      - run: 
          name: Frontend build
          command: |
            cd frontend
            npm install
            npm run build
      - run:
          command: |
            pwd
            ls -larth 
      - save_cache:
          paths: [frontend/node_modules]
          key: UdaPeople_Product-{{ checksum "package-lock.json" }}


  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: UdaPeople_Product-{{ checksum "package-lock.json" }}
      - run: 
          name: Backend Build
          command: |
            cd backend
            npm install
            npm run build
      - run:
          command: |
            pwd
            ls -larth 
      - save_cache:
          paths: [backend/node_modules]
          key: UdaPeople_Product-{{ checksum "package-lock.json" }}



workflows:
  default:
    jobs:
      - build-backend
      - build-frontend
