version: 2.1


orbs: 
    slack: circleci/slack@4.10.1
    
    
commands:
    notify_on_failure:
        steps:
          - slack/notify:
              event: fail
              channel: cicd-pipeline
              template: basic_fail_1

jobs:

  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - frontendUdaPeople_Product-{{ checksum "frontend/package-lock.json" }}
      - run: 
          name: Frontend build
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontendUdaPeople_Product-{{ checksum "frontend/package-lock.json" }}


  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - backendUdaPeople_Product-{{ checksum "backend/package-lock.json" }}
      - run: 
          name: Backend Build
          command: |
            cd backend
            npm install
            npm run build
      - run:
          command: |
            pwd
            ls -larth 
      - save_cache:
          paths: [backend/node_modules]
          key: backendUdaPeople_Product-{{ checksum "backend/package-lock.json" }}



  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - backendUdaPeople_Product-{{ checksum "backend/package-lock.json" }}
      - run:    
          name: Backend Test
          command: |
            cd backend
            npm install
            npm run test    

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - frontendUdaPeople_Product-{{ checksum "frontend/package-lock.json" }}
      - run:    
          name: Frontend Test
          command: |
            cd frontend
            npm install
            npm run test


  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - backendUdaPeople_Product-{{ checksum "backend/package-lock.json" }}
      - run:    
          name: Backend Scan
          command: |
            cd backend
            npm install
            npm audit fix --force --audit-level=critical
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical       
      - notify_on_failure
 

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - frontendUdaPeople_Product-{{ checksum "frontend/package-lock.json" }}
      - run:    
          name: Frontend Scan
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical


  notify_on_success:
      docker:
        - image: cimg/base:stable
      steps:
        - slack/notify:
            event: pass
            channel: cicd-pipeline
            template: success_tagged_deployment_1           

          
workflows:
  default:
    jobs:
      - build-backend
      - build-frontend
      - test-backend:
          requires:
            - build-backend
      - test-frontend:
          requires:
            - build-frontend
      - scan-backend:
          requires:
            - build-backend
      - scan-frontend:
          requires:
            - build-frontend
      - notify_on_success:
          requires:
            - scan-backend
            - scan-frontend
